-- TABELA PESSOA
CREATE TABLE PESSOA (
    ID INT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F'))
);

-- TABELA ENDEREÇO
CREATE TABLE ENDERECO (
    ID INT PRIMARY KEY,
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    COMPLEMENTO VARCHAR(40),
    NUMERO INT,
    CEP VARCHAR(8),
    SITUACAO CHAR(1) CHECK (SITUACAO IN ('A', 'I')),
    ID_PESSOA INT NOT NULL,
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID)
);

-- SEQUÊNCIAS PARA ID
CREATE SEQUENCE PESSOA_SEQ START 1;
CREATE SEQUENCE ENDERECO_SEQ START 1;

-- ÍNDICE PARA ID_PESSOA EM ENDERECO
CREATE INDEX IDX_ID_PESSOA ON ENDERECO(ID_PESSOA)